# Generated by Django 5.2.3 on 2025-08-06 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_ordertracking_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracking',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='store.order'),
        ),
    ]
